### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by Labunskyi** [Labunskyi/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by ghost** [comment]
Has star on the Hollywood Walk of Fame.
Has written up to 19 books on business, financial, or political topics.

**Comment by Labunskyi** [comment]
the best
